### ISSUE TITLE
Automatic application on SiteTree

### ISSUE THREAD

**Issue by nyeholt** [nglasl/silverstripe-fusion#6] opened 2016-04-25 11:42 UTC
Just a consideration - for some systems, the auto-addition to sitetree can be problematic if there's a _lot_ of other tags on content (added from other Tag types), in that it makes loading a page for editing somewhat slow. What're your thoughts around making it a user-config option?

**Comment by nglasl** [comment] 2016-06-10 06:31
This has been resolved in the latest round of changes, basically by including a new configuration around `tag_type_exclusions`. This will purge any fusion tags that *only* contain an excluded tag type, therefore preventing the tagging dropdown from causing the browser to hang (when you have a specific tag type that shouldn't really be available for tagging, likely due to it being automated such as microblog post tags). I've confirmed this isn't a great issue at present, and have therefore opted to only push these changes into the **3.2** version. There's no release just yet, but that will come soon.

**Closed by nglasl** 2016-06-10 06:31 UTC
